import { migration, numArray } from "../../../src/index";

// Generated by bursztyn. Fill in up(), then delete the names from `pending`.
// Carried over untouched: strings, city, stopLookup, stopId, stopName, stopLat, stopRoutes
export default migration({
    id: "0001_add_stop_bearing",
    defines: {
        stopBearing: numArray(Uint16Array),
    },
    up({ previous, builders }) {
        // stopBearing — new field (num:Uint16Array), no source data yet
        const stopId = previous.get<Uint32Array>("stopId");
        for (let i = 0; i < stopId.length; i++) {
            builders.stopBearing.push(0);
        }
    },
});
