import { migration } from "../../../src/index";

// Generated by bursztyn. Nothing to fill in — every field is carried over.
export default migration({
    id: "0002_rename_stop_name_to_stop_label",
    renames: { stopName: "stopLabel" },
});
