#!/usr/bin/env node
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { enforcement } from "./bundle.ts";
import { diffManifest, inspect, isSnapshot } from "./format.ts";
import { planGeneration, renameCandidates, type SchemaChange } from "./generate.ts";
import {
    emptyJournal,
    parseJournal,
    snapshotManifest,
    snapshotPath,
    journalPath,
    type Journal,
    type SchemaSnapshot,
} from "./journal.ts";
import { readSnapshotFile } from "./io.ts";
import { Schema } from "./schema.ts";

const tty = process.stdout.isTTY === true;
const paint = (code: string, text: string) => (tty ? `[${code}m${text}[0m` : text);
const bold = (text: string) => paint("1", text);
const dim = (text: string) => paint("2", text);
const red = (text: string) => paint("31", text);
const green = (text: string) => paint("32", text);
const yellow = (text: string) => paint("33", text);

const write = (text: string) => process.stdout.write(`${text}\n`);
const fail = (text: string): never => {
    process.stderr.write(`${red("✗")} ${text}\n`);
    process.exit(1);
};

const USAGE = `${bold("bursztyn")} — schema snapshots with generated migrations

  bursztyn generate [--name <name>] [--rename <old>=<new>] [--split]
  bursztyn status
  bursztyn inspect <file.brsz> [--json] [--sort=bytes|name|order] [--top=N]

Options:
  --schema <path>   schema module (default: bursztyn.config.json → "schema")
  --out <dir>       migrations folder (default: ./bursztyn)
  --config <path>   config file (default: ./bursztyn.config.json)
`;

const args = process.argv.slice(2);
const command = args[0];

const flag = (name: string): string | undefined => {
    const inline = args.find((arg) => arg.startsWith(`--${name}=`));
    if (inline) return inline.slice(name.length + 3);

    const index = args.indexOf(`--${name}`);
    return index !== -1 ? args[index + 1] : undefined;
};

const flags = (name: string): string[] =>
    args
        .map((arg, index) =>
            arg === `--${name}` ? args[index + 1] : arg.startsWith(`--${name}=`) ? arg.slice(name.length + 3) : undefined,
        )
        .filter((value): value is string => value !== undefined);

interface Config {
    schema: string;
    out: string;
    importFrom: string;
}

const loadConfig = async (): Promise<Config> => {
    const path = resolve(flag("config") ?? "bursztyn.config.json");
    let file: Partial<Config> = {};

    try {
        file = JSON.parse(await readFile(path, "utf8")) as Partial<Config>;
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }

    const schema = flag("schema") ?? file.schema;
    if (!schema) {
        fail(
            `No schema module configured.\n\n  Create ${bold("bursztyn.config.json")}:\n\n` +
                `    { "schema": "./src/schema.ts", "out": "./bursztyn" }\n\n` +
                `  …or pass ${bold("--schema <path>")}.`,
        );
    }

    return {
        schema: schema!,
        out: flag("out") ?? file.out ?? "./bursztyn",
        importFrom: file.importFrom ?? "bursztyn",
    };
};

const ensureBundleStub = async (out: string, importFrom: string) => {
    const path = resolve(out, "index.ts");
    if (await readFile(path, "utf8").then(() => true).catch(() => false)) return;

    await mkdir(dirname(path), { recursive: true });
    await writeFile(
        path,
        `// Generated by bursztyn — do not edit.\n` +
            `import { defineMigrations } from "${importFrom}";\n\n` +
            `export default defineMigrations({\n    hash: "0",\n    entries: [],\n});\n`,
    );
};

const loadSchema = async (path: string): Promise<Schema<any>> => {
    enforcement.enabled = false;

    const absolute = isAbsolute(path) ? path : resolve(path);
    let module: Record<string, unknown>;

    try {
        module = (await import(pathToFileURL(absolute).href)) as Record<string, unknown>;
    } catch (error) {
        if (absolute.endsWith(".ts") && !("Bun" in globalThis) && !("Deno" in globalThis)) {
            return fail(
                `Could not import ${path}.\n\n  Node cannot import TypeScript directly — run the CLI with Bun:\n\n` +
                    `    bun bursztyn ${args.join(" ")}\n\n  ${dim(String(error))}`,
            );
        }
        return fail(`Could not import ${path}\n\n  ${String(error)}`);
    }

    for (const value of Object.values(module)) {
        if (value instanceof Schema) return value;
    }

    return fail(
        `${path} does not export a schema.\n\n  Expected something built with ${bold("defineSchema()")}.`,
    );
};

const readJournal = async (out: string): Promise<Journal> => {
    try {
        return parseJournal(await readFile(resolve(journalPath(out)), "utf8"));
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return emptyJournal();
        throw error;
    }
};

const readSnapshot = async (out: string, version: number): Promise<SchemaSnapshot> =>
    JSON.parse(await readFile(resolve(snapshotPath(out, version)), "utf8")) as SchemaSnapshot;

const lastSnapshot = async (out: string, journal: Journal): Promise<SchemaSnapshot | null> => {
    const latest = journal.entries.at(-1);
    return latest ? readSnapshot(out, latest.version) : null;
};

const ask = async (question: string): Promise<boolean> => {
    const { createInterface } = await import("node:readline/promises");
    const rl = createInterface({ input: process.stdin, output: process.stdout });

    try {
        const answer = await rl.question(`${question} ${dim("[y/N]")} `);
        return answer.trim().toLowerCase().startsWith("y");
    } finally {
        rl.close();
    }
};

const describeChangeLines = (change: SchemaChange): string[] => {
    const lines: string[] = [];
    for (const field of change.added) lines.push(`  ${green("+")} ${field.name} ${dim(field.signature)}`);
    for (const field of change.removed) lines.push(`  ${red("-")} ${field.name} ${dim(field.signature)}`);
    for (const field of change.changed) {
        lines.push(`  ${yellow("~")} ${field.name} ${dim(`${field.before} → ${field.after}`)}`);
    }
    for (const entry of change.renamed) {
        lines.push(`  ${yellow("→")} ${entry.from} ${dim("renamed to")} ${entry.to}`);
    }
    if (change.reordered) lines.push(`  ${dim("· fields reordered")}`);
    return lines;
};

const runGenerate = async () => {
    const config = await loadConfig();
    await ensureBundleStub(config.out, config.importFrom);
    const schema = await loadSchema(config.schema);
    const journal = await readJournal(config.out);
    const previous = await lastSnapshot(config.out, journal);

    const renames: Record<string, string> = {};
    for (const pair of flags("rename")) {
        const [from, to] = pair.split("=");
        if (!from || !to) fail(`--rename expects old=new, got "${pair}"`);
        renames[from] = to;
    }

    if (previous) {
        const diff = diffManifest(snapshotManifest(previous), schema.compiled.layout);
        const candidates = renameCandidates(diff).filter(
            (candidate) => renames[candidate.removed] === undefined,
        );

        for (const candidate of candidates) {
            const question =
                `${yellow("?")} Is ${bold(candidate.removed)} renamed to ${bold(candidate.added)}` +
                ` ${dim(`(both ${candidate.signature})`)}?`;

            if (!tty) {
                fail(
                    `Ambiguous change: ${candidate.removed} disappeared and ${candidate.added} appeared, ` +
                        `both ${candidate.signature}.\n\n` +
                        `  If it is a rename:  bursztyn generate --rename ${candidate.removed}=${candidate.added}\n` +
                        `  If it is not, run this in a terminal and answer the prompt.`,
                );
            }

            if (await ask(question)) renames[candidate.removed] = candidate.added;
        }
    }

    const result = planGeneration({
        compiled: schema.compiled,
        journal,
        previous,
        out: config.out,
        importFrom: config.importFrom,
        name: flag("name"),
        renames,
        timestamp: new Date().toISOString(),
    });

    if (result.status === "up-to-date") {
        write(`${green("✓")} Schema is up to date ${dim(`(version ${previous!.version})`)}`);
        return;
    }

    for (const file of result.files) {
        await mkdir(dirname(resolve(file.path)), { recursive: true });
        await writeFile(resolve(file.path), file.content);
    }

    if (result.status === "initial") {
        write(`${green("✓")} Initialised ${bold(config.out)} at version 0`);
        write(dim(`  ${schema.compiled.layout.length} fields recorded in meta/0000_snapshot.json`));
        write("");
        write(`  Import the generated bundle in your schema module:`);
        write(dim(`    import migrations from "${config.out}";`));
        write(dim(`    export const schema = defineSchema({ fields, migrations });`));
        return;
    }

    write(`${green("✓")} ${bold(result.id!)}`);
    write("");
    for (const line of describeChangeLines(result.change!)) write(line);
    write("");

    const pending = result.change!.added.length + result.change!.changed.length;
    if (pending === 0) {
        write(`  ${green("Nothing to fill in")} — every field is carried over untouched.`);
        return;
    }

    const file = result.files[0].path;
    write(
        `  ${yellow(`⚠ ${pending} field${pending === 1 ? "" : "s"} need${pending === 1 ? "s" : ""} data.`)}`,
    );
    write(`  Open ${bold(file)}, fill in ${bold("up()")}, then delete the names from ${bold("pending")}.`);
    write("");
    write(`  ${dim("Until then the app refuses to start.")}`);
    process.exitCode = 1;
};

const runStatus = async () => {
    const config = await loadConfig();
    await ensureBundleStub(config.out, config.importFrom);
    const schema = await loadSchema(config.schema);
    const journal = await readJournal(config.out);
    const previous = await lastSnapshot(config.out, journal);

    if (!previous) {
        write(`${yellow("!")} ${bold(config.out)} is empty — run ${bold("bursztyn generate")}`);
        process.exitCode = 1;
        return;
    }

    const drifted = BigInt(previous.hash) !== schema.compiled.hash;
    if (drifted) {
        write(`${red("✗")} Schema has uncommitted changes ${dim(`(version ${previous.version})`)}`);
        write("");
        const diff = diffManifest(snapshotManifest(previous), schema.compiled.layout);
        for (const entry of diff) {
            if (entry.kind === "added") write(`  ${green("+")} ${entry.name} ${dim(entry.signature)}`);
            if (entry.kind === "removed") write(`  ${red("-")} ${entry.name} ${dim(entry.signature)}`);
            if (entry.kind === "changed") {
                write(`  ${yellow("~")} ${entry.name} ${dim(`${entry.before} → ${entry.after}`)}`);
            }
        }
        write("");
        write(`  Run:  ${bold("bursztyn generate")}`);
        process.exitCode = 1;
        return;
    }

    const bundle = await import(pathToFileURL(resolve(config.out, "index.ts")).href)
        .then((module) => module.default)
        .catch(() => null);

    if (bundle?.unfinished?.length) {
        write(`${red("✗")} Unfinished migrations`);
        write("");
        for (const entry of bundle.unfinished) {
            write(`  ${bold(entry.id)}`);
            for (const name of entry.pending) write(`    ${yellow("-")} ${name}`);
        }
        write("");
        write(`  Fill in ${bold("up()")}, then delete those names from ${bold("pending")}.`);
        process.exitCode = 1;
        return;
    }

    write(`${green("✓")} Up to date ${dim(`— version ${previous.version}, ${previous.fields.length} fields`)}`);
};

const formatBytes = (bytes: number): string => {
    if (bytes < 1024) return `${bytes} B`;
    const units = ["KiB", "MiB", "GiB"];
    let value = bytes / 1024;
    let unit = 0;
    while (value >= 1024 && unit < units.length - 1) {
        value /= 1024;
        unit++;
    }
    return `${value.toFixed(value < 10 ? 2 : 1)} ${units[unit]}`;
};

const runInspect = async () => {
    const file = args[1];
    if (!file) fail("bursztyn inspect <file.brsz>");

    const bytes = await readSnapshotFile(file);
    if (!isSnapshot(bytes)) fail(`${file} is not a bursztyn snapshot.`);

    const info = inspect(bytes);
    const sort = flag("sort") ?? "bytes";
    const fields = [...info.fields];

    if (sort === "bytes") fields.sort((a, b) => b.bytes - a.bytes);
    if (sort === "name") fields.sort((a, b) => a.name.localeCompare(b.name));

    if (args.includes("--json")) {
        write(JSON.stringify({ ...info, schemaHash: info.schemaHash.toString(), fields }, null, 2));
        return;
    }

    const rows = fields.slice(0, Number(flag("top") ?? fields.length));
    const nameWidth = Math.max(5, ...rows.map((row) => row.name.length));
    const sizeWidth = Math.max(5, ...rows.map((row) => formatBytes(row.bytes).length));

    write(bold(file));
    write(dim(`  format v${info.formatVersion}  schema v${info.schemaVersion}  hash ${info.schemaHash}`));
    write(`  ${formatBytes(info.totalBytes)} across ${info.fields.length} fields\n`);

    for (const row of rows) {
        const share = info.totalBytes > 0 ? (row.bytes / info.totalBytes) * 100 : 0;
        write(
            `  ${row.name.padEnd(nameWidth)}  ${formatBytes(row.bytes).padStart(sizeWidth)}  ` +
                `${share.toFixed(1).padStart(5)}%  ${dim(row.signature)}`,
        );
    }

    if (rows.length < fields.length) write(dim(`\n  … ${fields.length - rows.length} more`));
};

switch (command) {
    case "generate":
        await runGenerate();
        break;
    case "status":
    case "check":
        await runStatus();
        break;
    case "inspect":
        await runInspect();
        break;
    case undefined:
    case "help":
    case "--help":
        write(USAGE);
        break;
    default:
        process.stderr.write(`${USAGE}\n`);
        fail(`Unknown command "${command}"`);
}
